Repository fga-eps-mds/2022-2-QuantiFGA, pull requests merged in 2023-01, with the labels that each got.

#105 docs: (#89) atualização do protótipo de alta
  docs/prototipo_alta_apos_R1.md
Labels: documentation

#125 feat: adição da api
  frontend/app/Quanti_FGA/__init__.py
  frontend/app/Quanti_FGA/__pycache__/__init__.cpython-39.pyc
  frontend/app/Quanti_FGA/__pycache__/settings.cpython-39.pyc
  frontend/app/Quanti_FGA/__pycache__/urls.cpython-39.pyc
  frontend/app/Quanti_FGA/__pycache__/wsgi.cpython-39.pyc
  frontend/app/Quanti_FGA/asgi.py
  frontend/app/Quanti_FGA/settings.py
  frontend/app/Quanti_FGA/urls.py
  frontend/app/Quanti_FGA/wsgi.py
  frontend/app/Quanti_FGA_Front/__init__.py
  frontend/app/Quanti_FGA_Front/__pycache__/__init__.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/__pycache__/admin.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/__pycache__/apps.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/__pycache__/models.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/__pycache__/serializers.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/__pycache__/urls.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/__pycache__/views.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/admin.py
  frontend/app/Quanti_FGA_Front/apps.py
  frontend/app/Quanti_FGA_Front/migrations/0001_initial.py
  frontend/app/Quanti_FGA_Front/migrations/__init__.py
  frontend/app/Quanti_FGA_Front/migrations/__pycache__/0001_initial.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/migrations/__pycache__/__init__.cpython-39.pyc
  frontend/app/Quanti_FGA_Front/models.py
  frontend/app/Quanti_FGA_Front/serializers.py
  frontend/app/Quanti_FGA_Front/tests.py
  frontend/app/Quanti_FGA_Front/urls.py
  frontend/app/Quanti_FGA_Front/views.py
  frontend/app/manage.py
  frontend/app/quanti_api/models.py
  frontend/app/quanti_api/views.py
  frontend/app/setup/__pycache__/__init__.cpython-39.pyc
  frontend/app/setup/__pycache__/settings.cpython-39.pyc
  frontend/app/setup/__pycache__/urls.cpython-39.pyc
  frontend/app/setup/__pycache__/wsgi.cpython-39.pyc
  frontend/app/setup/urls.py
Labels: enhancement

#127 feat: Django - Frontend
  frontend/Djando- Teste FrontEnd/mysite/polls/templates/polls/index.html
  frontend/Djando- Teste FrontEnd/mysite/static/css/reset.css
  frontend/Djando- Teste FrontEnd/mysite/static/css/style.css
  frontend/Djando- Teste FrontEnd/mysite/static/img/Prantinea.svg
  frontend/Djando- Teste FrontEnd/mysite/static/img/QuantiFGA-logo.png
  frontend/Djando- Teste FrontEnd/mysite/static/img/fundo.png
  frontend/Djando- Teste FrontEnd/mysite/static/img/logo.png
  frontend/Djando- Teste FrontEnd/mysite/static/img/louros.png
  frontend/Djando- Teste FrontEnd/mysite/static/img/photothumb.db
  frontend/Djando- Teste FrontEnd/mysite/static/img/quantiFGA-removebg-preview.png
  frontend/Djando- Teste FrontEnd/mysite/static/js/script.js
  frontend/index.html
  frontend/reset.css
  frontend/script.js
  frontend/style.css
Labels: enhancement

#129 (#113) refactor: alteração do webscrapping - exceções
  backend/ColetaSigaaPublico.py
  backend/Padronizacao_Nome_Salas.md
  backend/calcularPercentuais.py
  backend/carregarDados.py
  backend/csvDadosAtualizados.csv
  backend/csvDadosColetados.csv
  backend/csvDadosDesprezados.csv
  backend/csvPrediosSalasLotacao.csv
  backend/preencherLotacaoSalas.py
  backend/separarHorarios.py
  backend/separarSalasCompostas.py
  backend/separarSalasCompostasEHorarios.py
  backend/testes/csvTesteHorariosSeparados.csv
  backend/testes/csvTesteLotacaoPredio.csv
  backend/testes/csvTestePorcentagens.csv
  backend/testes/csvTesteSalasHorariosSeparadas.csv
  backend/testes/csvTesteSalasSeparadas.csv
  backend/testesUnitarios/read.me
  docs/Excecoes_tratamento_posterior_em_versoes_futuras.md
Labels: enhancement

#131 (#99) treinamento testes unitarios e definição de tarefas
  backend/TestesUnitarios.py
Labels: enhancement, training

#134 Integração contínua (CI) - Pipelines
  .github/workflows/django.yml
Labels: enhancement

#136 Test separar horarios
  backend/TestesUnitarios.py
  backend/__pycache__/calcularPercentuais.cpython-311.pyc
  backend/__pycache__/calcularPercentuais.cpython-39.pyc
  backend/__pycache__/carregarDados.cpython-311.pyc
  backend/__pycache__/preencherLotacaoSalas.cpython-311.pyc
  backend/__pycache__/preencherLotacaoSalas.cpython-39.pyc
  backend/__pycache__/separarSalasCompostasEHorarios.cpython-311.pyc
  backend/__pycache__/separarSalasCompostasEHorarios.cpython-39.pyc
  backend/testesUnitarios/csvTeste1.csv
  backend/testesUnitarios/csvTeste2.csv
  backend/testesUnitarios/csvTeste3.csv
  backend/testesUnitarios/csvTesteUnitLotacaoPredio.csv
  backend/testesUnitarios/csvTesteUnitPorcentagens.csv
  backend/testesUnitarios/csvTesteUnitSalasHorariosSeparadas.csv
Labels: enhancement, test

#149 Teste para método separar salas
  backend/TestesUnitarios.py
Labels: enhancement, test

#148 Feat automating scrapping to database
  backend/ColetaSigaaPublico.py
  backend/TestesUnitarios.py
Labels: enhancement

#153 Fix: Correção merge
  backend/TestesUnitarios.py
Labels: bug, fixing

#154 doc: Adicionando prototipo
  docs/Prototipo-Alta-Final.md
  docs/Protótipo.md
  docs/prototipo.md
  docs/prototipo_alta_apos_R1.md
Labels: documentation, prototype

#159 Update TestesUnitarios.py
  backend/TestesUnitarios.py
Labels: tests

#162 docs: (#144) Atualização do Story Map
  docs/Story-Mapping.md
  docs/img/Incremetos.png
  docs/img/MVP.png
  docs/img/Story Map (INCREMENTO).png
  docs/img/Story Map (MVP).png
Labels: documentation

#163 Nova Gitpage
  docs/img_gitpage/Edi.png
  docs/img_gitpage/Felipe.png
  docs/img_gitpage/Gabriel.png
  docs/img_gitpage/Julia.png
  docs/img_gitpage/Pedro.png
  docs/img_gitpage/Raquel.png
  docs/img_gitpage/Vera.png
  docs/img_gitpage/Zenilda.png
  docs/img_gitpage/analise_dados.svg
  docs/img_gitpage/arquitetura-responsivo.svg
  docs/img_gitpage/arquitetura.svg
  docs/img_gitpage/dados_disciplina.svg
  docs/img_gitpage/engrenagem.png
  docs/img_gitpage/faculdade_gama.png
  docs/img_gitpage/github_logo.png
  docs/img_gitpage/louros.svg
  docs/img_gitpage/main-background-test.svg
  docs/img_gitpage/main_background.svg
  docs/img_gitpage/main_background_new.svg
  docs/img_gitpage/metabase_logo.png
  docs/img_gitpage/page_transparent.svg
  docs/img_gitpage/portinha_abrindo.svg
  docs/img_gitpage/quantiFGA_logo.png
  docs/img_gitpage/unb_logo.png
  docs/index.html
  docs/index_pg2.html
  docs/querry.css
  docs/reset.css
  docs/style.css
  docs/style_pg2.css
Labels: deploy, frontend

#161 Atualizacao prototipo
  docs/Protótipo.md
Labels: documentation, prototype

#164 docs: atualizando documentacao
  README.md
  docs/Documento-Arquitetura.md
  docs/Guia_de_contribuição.md
  docs/Requisitos.md
  docs/img/arquitetura_canva.png
Labels: documentation, fixing

#165 test: Atualização dos testes unitários
  backend/TestesUnitarios.py
Labels: tests, unit test
