Repository fga-eps-mds/2022-2-QuantiFGA, pull requests merged in 2023-02, with the labels that each got.

#173 docs: criação do documento de Politica de segurança SECURITY.md
  SECURITY.md
Labels: documentation

#191 Atualização readme
  README.md
Labels: documentation, enhancement

#193 refactor: nome CI
  .github/workflows/pythonCI.yml
Labels: documentation, fixing

#194 Atualizacao codecov (98% de cobertura)
  README.md
  backend/htmlcov/TestesUnitarios_py.html
  backend/htmlcov/calcularPercentuais_py.html
  backend/htmlcov/carregarDados_py.html
  backend/htmlcov/index.html
  backend/htmlcov/preencherLotacaoSalas_py.html
  backend/htmlcov/separarSalasCompostasEHorarios_py.html
  backend/htmlcov/status.json
Labels: tests

#195 refactor: mudando nome interno
  .github/workflows/pythonCI.yml
Labels: documentation, fixing

#198 docs: criacao do post-mortem
  POST_MORTEM.md
Labels: documentation, important
